function [Time, Data] = importOsziMeasFcn(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, DATA] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [TIME, DATA] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [Time, Data] = importfile("C:\VersionControl\Git\TIC2000_DCDC_LED\Data\ExternalMeasurements\Step0_40.CSV", [1, Inf]);
%
%  See also READTABLE.
% Copyright 2020 - 2020 The MathWorks, Inc.
% Auto-generated by MATLAB on 14-Feb-2020 08:56:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Time", "Data"];
opts.SelectedVariableNames = ["Time", "Data"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time = tbl.Time;
Data = tbl.Data;
end