% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Jul-2019 09:36:03
%  MATLAB version: 9.6.0.1135713 (R2019a) Update 3

% Copyright 2020 - 2020 The MathWorks, Inc.
% -------------------------------------------------------------------
Rhytmus = 0.2;           
%% Supervisory Logic parameters:

SEPIC_Efficiency = Simulink.Parameter;
SEPIC_Efficiency.Value = single(0.88);
SEPIC_Efficiency.CoderInfo.StorageClass = 'ExportedGlobal';
SEPIC_Efficiency.CoderInfo.Alias = '';
SEPIC_Efficiency.CoderInfo.Alignment = -1;
SEPIC_Efficiency.Description = '';
SEPIC_Efficiency.DataType = 'single';
SEPIC_Efficiency.Min = [];
SEPIC_Efficiency.Max = [];
SEPIC_Efficiency.DocUnits = '';

%% voltage controller
VoltCtrlr_IGain = Simulink.Parameter;
VoltCtrlr_IGain.Value = single(1.36305535761967);
VoltCtrlr_IGain.CoderInfo.StorageClass = 'ExportedGlobal';
VoltCtrlr_IGain.CoderInfo.Alias = '';
VoltCtrlr_IGain.CoderInfo.Alignment = -1;
VoltCtrlr_IGain.Description = '';
VoltCtrlr_IGain.DataType = 'single';
VoltCtrlr_IGain.Min = [];
VoltCtrlr_IGain.Max = [];
VoltCtrlr_IGain.DocUnits = '';


VoltCtrlr_PGain = Simulink.Parameter;
VoltCtrlr_PGain.Value = single(0.00550519269956728);
VoltCtrlr_PGain.CoderInfo.StorageClass = 'ExportedGlobal';
VoltCtrlr_PGain.CoderInfo.Alias = '';
VoltCtrlr_PGain.CoderInfo.Alignment = -1;
VoltCtrlr_PGain.Description = '';
VoltCtrlr_PGain.DataType = 'single';
VoltCtrlr_PGain.Min = [];
VoltCtrlr_PGain.Max = [];
VoltCtrlr_PGain.DocUnits = '';

%Exponential polynomial for DC max a*x^b+c:
VoltCtrlr_dcMax_a = Simulink.Parameter;
VoltCtrlr_dcMax_a.Value = single(-0.3963439);
VoltCtrlr_dcMax_a.CoderInfo.StorageClass = 'ExportedGlobal';
VoltCtrlr_dcMax_a.CoderInfo.Alias = '';
VoltCtrlr_dcMax_a.CoderInfo.Alignment = -1;
VoltCtrlr_dcMax_a.Description = '';
VoltCtrlr_dcMax_a.DataType = 'single';
VoltCtrlr_dcMax_a.Min = [];
VoltCtrlr_dcMax_a.Max = [];
VoltCtrlr_dcMax_a.DocUnits = '';

VoltCtrlr_dcMax_b = Simulink.Parameter;
VoltCtrlr_dcMax_b.Value = single(-0.3861287);
VoltCtrlr_dcMax_b.CoderInfo.StorageClass = 'ExportedGlobal';
VoltCtrlr_dcMax_b.CoderInfo.Alias = '';
VoltCtrlr_dcMax_b.CoderInfo.Alignment = -1;
VoltCtrlr_dcMax_b.Description = '';
VoltCtrlr_dcMax_b.DataType = 'single';
VoltCtrlr_dcMax_b.Min = [];
VoltCtrlr_dcMax_b.Max = [];
VoltCtrlr_dcMax_b.DocUnits = '';

VoltCtrlr_dcMax_c = Simulink.Parameter;
VoltCtrlr_dcMax_c.Value = single(1.0183439);
VoltCtrlr_dcMax_c.CoderInfo.StorageClass = 'ExportedGlobal';
VoltCtrlr_dcMax_c.CoderInfo.Alias = '';
VoltCtrlr_dcMax_c.CoderInfo.Alignment = -1;
VoltCtrlr_dcMax_c.Description = '';
VoltCtrlr_dcMax_c.DataType = 'single';
VoltCtrlr_dcMax_c.Min = [];
VoltCtrlr_dcMax_c.Max = [];
VoltCtrlr_dcMax_c.DocUnits = '';

%% current controller
CurrCtrlr_IGain = Simulink.Parameter;
CurrCtrlr_IGain.Value = single(0.1701);
CurrCtrlr_IGain.CoderInfo.StorageClass = 'ExportedGlobal';
CurrCtrlr_IGain.CoderInfo.Alias = '';
CurrCtrlr_IGain.CoderInfo.Alignment = -1;
CurrCtrlr_IGain.Description = '';
CurrCtrlr_IGain.DataType = 'single';
CurrCtrlr_IGain.Min = [];
CurrCtrlr_IGain.Max = [];
CurrCtrlr_IGain.DocUnits = '';


CurrCtrlr_PGain = Simulink.Parameter;
CurrCtrlr_PGain.Value = single(8.505e-5);
CurrCtrlr_PGain.CoderInfo.StorageClass = 'ExportedGlobal';
CurrCtrlr_PGain.CoderInfo.Alias = '';
CurrCtrlr_PGain.CoderInfo.Alignment = -1;
CurrCtrlr_PGain.Description = '';
CurrCtrlr_PGain.DataType = 'single';
CurrCtrlr_PGain.Min = [];
CurrCtrlr_PGain.Max = [];
CurrCtrlr_PGain.DocUnits = '';

CurrCtrlr_IC_Table = Simulink.Parameter;
CurrCtrlr_IC_Table.Value = single([    0.6239    0.3420    0.2082    0.1391    0.1003    0.0765    0.0612    0.0502;...
                                0.8100    0.8100    0.5512    0.3684    0.2655    0.2027    0.1615    0.1331]);
CurrCtrlr_IC_Table.CoderInfo.StorageClass = 'ExportedGlobal';
CurrCtrlr_IC_Table.CoderInfo.Alias = '';
CurrCtrlr_IC_Table.CoderInfo.Alignment = -1;
CurrCtrlr_IC_Table.Description = '';
CurrCtrlr_IC_Table.DataType = 'single';
CurrCtrlr_IC_Table.Min = [];
CurrCtrlr_IC_Table.Max = [];
CurrCtrlr_IC_Table.DocUnits = '';

CurrCtrlr_IC_CurrBrkpnt = Simulink.Parameter;
CurrCtrlr_IC_CurrBrkpnt.Value = single([40 100]);
CurrCtrlr_IC_CurrBrkpnt.CoderInfo.StorageClass = 'ExportedGlobal';
CurrCtrlr_IC_CurrBrkpnt.CoderInfo.Alias = '';
CurrCtrlr_IC_CurrBrkpnt.CoderInfo.Alignment = -1;
CurrCtrlr_IC_CurrBrkpnt.Description = '';
CurrCtrlr_IC_CurrBrkpnt.DataType = 'single';
CurrCtrlr_IC_CurrBrkpnt.Min = [];
CurrCtrlr_IC_CurrBrkpnt.Max = [];
CurrCtrlr_IC_CurrBrkpnt.DocUnits = '';

CurrCtrlr_IC_VoltBrkpnt = Simulink.Parameter;
CurrCtrlr_IC_VoltBrkpnt.Value = single([17 17.5 18 18.5 19 19.5 20 20.5]);
CurrCtrlr_IC_VoltBrkpnt.CoderInfo.StorageClass = 'ExportedGlobal';
CurrCtrlr_IC_VoltBrkpnt.CoderInfo.Alias = '';
CurrCtrlr_IC_VoltBrkpnt.CoderInfo.Alignment = -1;
CurrCtrlr_IC_VoltBrkpnt.Description = '';
CurrCtrlr_IC_VoltBrkpnt.DataType = 'single';
CurrCtrlr_IC_VoltBrkpnt.Min = [];
CurrCtrlr_IC_VoltBrkpnt.Max = [];
CurrCtrlr_IC_VoltBrkpnt.DocUnits = '';

